#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu May 14 01:03:23 -03 2020
# SW Build 2729669 on Thu Dec  5 04:48:12 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto cec3628a41294c55b2ca3e0e7e07050a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_1a_behav xil_defaultlib.tb_1a -log elaborate.log"
xelab -wto cec3628a41294c55b2ca3e0e7e07050a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_1a_behav xil_defaultlib.tb_1a -log elaborate.log

