#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Apr 20 12:09:09 -03 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 75d7aab472ad4b08b4bfeb663f2ec9bb --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_mod7_counter_func_synth xil_defaultlib.tb_mod7_counter -log elaborate.log"
xelab -wto 75d7aab472ad4b08b4bfeb663f2ec9bb --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_mod7_counter_func_synth xil_defaultlib.tb_mod7_counter -log elaborate.log

