#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Apr 07 12:19:32 -03 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 34575825a9944e2183f994245447a99b --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_eq2_func_synth xil_defaultlib.tb_eq2 -log elaborate.log"
xelab -wto 34575825a9944e2183f994245447a99b --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_eq2_func_synth xil_defaultlib.tb_eq2 -log elaborate.log

