#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Apr 14 15:10:22 -03 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 03ee8179e1d4465198482efe1c33332d --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_EP3_behav xil_defaultlib.tb_EP3 -log elaborate.log"
xelab -wto 03ee8179e1d4465198482efe1c33332d --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_EP3_behav xil_defaultlib.tb_EP3 -log elaborate.log

