#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Jun 06 17:45:27 -03 2020
# SW Build 2729669 on Thu Dec  5 04:48:12 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 95b8148bc8114d3e9ab5c535b2d22be9 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_VGA_behav xil_defaultlib.tb_VGA -log elaborate.log"
xelab -wto 95b8148bc8114d3e9ab5c535b2d22be9 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_VGA_behav xil_defaultlib.tb_VGA -log elaborate.log

