# Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]

# Switches
#set_property PACKAGE_PIN V17 [get_ports {din[0]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {din[0]}]
#set_property PACKAGE_PIN V16 [get_ports {din[1]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {din[1]}]
#set_property PACKAGE_PIN W16 [get_ports {din[2]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {din[2]}]
#set_property PACKAGE_PIN W17 [get_ports {din[3]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {din[3]}]
#set_property PACKAGE_PIN W15 [get_ports {din[4]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {din[4]}]
#set_property PACKAGE_PIN V15 [get_ports {din[5]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {din[5]}]
#set_property PACKAGE_PIN W14 [get_ports {din[6]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {din[6]}]
#set_property PACKAGE_PIN W13 [get_ports {din[7]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {din[7]}]
#set_property PACKAGE_PIN V2 [get_ports {din[8]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {din[8]}]
#set_property PACKAGE_PIN T3 [get_ports {din[9]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {din[9]}]
#set_property PACKAGE_PIN T2 [get_ports {din[10]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {din[10]}]
#set_property PACKAGE_PIN R3 [get_ports {din[11]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {din[11]}]
#set_property PACKAGE_PIN W2 [get_ports {din[12]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {din[12]}]
#set_property PACKAGE_PIN U1 [get_ports {din[13]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {din[13]}]
#set_property PACKAGE_PIN T1 [get_ports {din[14]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {din[14]}]
#set_property PACKAGE_PIN R2 [get_ports {din[15]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {din[15]}]	

#Buttons
set_property PACKAGE_PIN U18 [get_ports reset]						
	set_property IOSTANDARD LVCMOS33 [get_ports reset]
#set_property PACKAGE_PIN T18 [get_ports start_btn]						
#	set_property IOSTANDARD LVCMOS33 [get_ports start_btn]	
#set_property PACKAGE_PIN T18 [get_ports wr_i2c]						
#	set_property IOSTANDARD LVCMOS33 [get_ports wr_i2c]
#set_property PACKAGE_PIN W19 [get_ports btnL]						
	#set_property IOSTANDARD LVCMOS33 [get_ports btnL]
#set_property PACKAGE_PIN T17 [get_ports btnR]						
	#set_property IOSTANDARD LVCMOS33 [get_ports btnR]
#set_property PACKAGE_PIN U17 [get_ports btnD]						
	#set_property IOSTANDARD LVCMOS33 [get_ports btnD]	
	


## Switches
set_property PACKAGE_PIN V17 [get_ports {hh_mm}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {hh_mm}]
#set_property PACKAGE_PIN V16 [get_ports {sw[1]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[1]}]
#set_property PACKAGE_PIN W16 [get_ports {sw[2]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[2]}]
#set_property PACKAGE_PIN W17 [get_ports {sw[3]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[3]}]
#set_property PACKAGE_PIN W15 [get_ports {sw[4]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[4]}]
#set_property PACKAGE_PIN V15 [get_ports {sw[5]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[5]}]
#set_property PACKAGE_PIN W14 [get_ports {sw[6]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[6]}]
#set_property PACKAGE_PIN W13 [get_ports {sw[7]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[7]}]
#set_property PACKAGE_PIN V2 [get_ports {sw[8]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[8]}]
#set_property PACKAGE_PIN T3 [get_ports {sw[9]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[9]}]
#set_property PACKAGE_PIN T2 [get_ports {sw[10]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[10]}]
#set_property PACKAGE_PIN R3 [get_ports {sw[11]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[11]}]
#set_property PACKAGE_PIN W2 [get_ports {sw[12]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[12]}]
#set_property PACKAGE_PIN U1 [get_ports {sw[13]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[13]}]
#set_property PACKAGE_PIN T1 [get_ports {sw[14]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[14]}]
set_property PACKAGE_PIN R2 [get_ports {start_btn}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {start_btn}]
 	
#Pmod Header JA
#Sch name = JA1
set_property PACKAGE_PIN J1 [get_ports {i2c_sclk}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i2c_sclk}]
#Sch name = JA2
set_property PACKAGE_PIN L2 [get_ports {i2c_sdat}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i2c_sdat}]
##Sch name = JA3
#set_property PACKAGE_PIN J2 [get_ports {JA[2]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {JA[2]}]
##Sch name = JA4
#set_property PACKAGE_PIN G2 [get_ports {JA[3]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {JA[3]}]
##Sch name = JA7
#set_property PACKAGE_PIN H1 [get_ports {JA[4]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {JA[4]}]
##Sch name = JA8
#set_property PACKAGE_PIN K2 [get_ports {JA[5]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {JA[5]}]
##Sch name = JA9
#set_property PACKAGE_PIN H2 [get_ports {JA[6]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {JA[6]}]
##Sch name = JA10
#set_property PACKAGE_PIN G3 [get_ports {JA[7]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {JA[7]}]	

# LEDs
set_property PACKAGE_PIN U16 [get_ports {i2c_idle}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i2c_idle}]
set_property PACKAGE_PIN E19 [get_ports {i2c_fail}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i2c_fail}]
set_property PACKAGE_PIN U19 [get_ports {i2c_done_tick}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i2c_done_tick}]
#set_property PACKAGE_PIN V19 [get_ports {led[3]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
#set_property PACKAGE_PIN W18 [get_ports {led[4]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
#set_property PACKAGE_PIN U15 [get_ports {led[5]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
#set_property PACKAGE_PIN U14 [get_ports {led[6]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
#set_property PACKAGE_PIN V14 [get_ports {led[7]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
#set_property PACKAGE_PIN V13 [get_ports {led[8]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {led[8]}]
#set_property PACKAGE_PIN V3 [get_ports {led[9]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {led[9]}]
#set_property PACKAGE_PIN W3 [get_ports {led[10]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {led[10]}]
#set_property PACKAGE_PIN U3 [get_ports {led[11]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {led[11]}]
#set_property PACKAGE_PIN P3 [get_ports {led[12]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {led[12]}]
#set_property PACKAGE_PIN N3 [get_ports {led[13]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {led[13]}]
#set_property PACKAGE_PIN P1 [get_ports {led[14]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {led[14]}]
#set_property PACKAGE_PIN L1 [get_ports {led[15]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {led[15]}]

### Output
    ##7 segment display
        set_property PACKAGE_PIN W7 [get_ports {sseg[0]}]					
            set_property IOSTANDARD LVCMOS33 [get_ports {sseg[0]}]
        set_property PACKAGE_PIN W6 [get_ports {sseg[1]}]					
            set_property IOSTANDARD LVCMOS33 [get_ports {sseg[1]}]
        set_property PACKAGE_PIN U8 [get_ports {sseg[2]}]					
            set_property IOSTANDARD LVCMOS33 [get_ports {sseg[2]}]
        set_property PACKAGE_PIN V8 [get_ports {sseg[3]}]					
            set_property IOSTANDARD LVCMOS33 [get_ports {sseg[3]}]
        set_property PACKAGE_PIN U5 [get_ports {sseg[4]}]					
            set_property IOSTANDARD LVCMOS33 [get_ports {sseg[4]}]
        set_property PACKAGE_PIN V5 [get_ports {sseg[5]}]					
            set_property IOSTANDARD LVCMOS33 [get_ports {sseg[5]}]
        set_property PACKAGE_PIN U7 [get_ports {sseg[6]}]					
            set_property IOSTANDARD LVCMOS33 [get_ports {sseg[6]}]
        set_property PACKAGE_PIN V7 [get_ports sseg[7]]							
            set_property IOSTANDARD LVCMOS33 [get_ports sseg[7]]        
    ##anodes
        set_property PACKAGE_PIN U2 [get_ports {an[0]}]					
            set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}]
        set_property PACKAGE_PIN U4 [get_ports {an[1]}]					
            set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
        set_property PACKAGE_PIN V4 [get_ports {an[2]}]					
            set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
        set_property PACKAGE_PIN W4 [get_ports {an[3]}]					
            set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]